import img from "../../../../images/landing/bth.jpg";

export const LANDING_TOUR_DATA = [
  {
    id: 1,
    imgBg: img,
    href: "",
    price: "100 000",
    title: "Binh Thuan1 - Viet Nam",
    des: "Lan đấm Nhàn thâm mắt",
  },
  {
    id: 2,
    imgBg: img,
    href: "",
    price: "100 000",
    title: "Binh Thuan2 - Viet Nam",
    des: "Lan đấm Nhàn thâm mắt",
  },
  {
    id: 3,
    imgBg: img,
    href: "",
    price: "100 000",
    title: "Binh Thuan3 - Viet Nam",
    des: "Lan đấm Nhàn thâm mắt",
  },
  {
    id: 4,
    imgBg: img,
    href: "",
    price: "100 000",
    title: "Binh Thuan4 - Viet Nam",
    des: "Lan đấm Nhàn thâm mắt",
  },
  {
    id: 5,
    imgBg: img,
    href: "",
    price: "100 000",
    title: "Binh Thuan1 - Viet Nam",
    des: "Lan đấm Nhàn thâm mắt",
  },
  {
    id: 6,
    imgBg: img,
    href: "",
    price: "100 000",
    title: "Binh Thuan2 - Viet Nam",
    des: "Lan đấm Nhàn thâm mắt",
  },
  {
    id: 7,
    imgBg: img,
    href: "",
    price: "100 000",
    title: "Binh Thuan3 - Viet Nam",
    des: "Lan đấm Nhàn thâm mắt",
  },
  {
    id: 8,
    imgBg: img,
    href: "",
    price: "100 000",
    title: "Binh Thuan4 - Viet Nam",
    des: "Lan đấm Nhàn thâm mắt",
  },
];
